name: Simple CI/CD

on:
  push:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build


  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4

      - name: Run tests
        run: npm test


  docker:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t my-app .


  deploy:
    runs-on: ubuntu-latest
    needs: docker

    steps:
      - name: Deploy message
        run: echo "Application Deployed Successfully 🚀"
